Paginate = 5
baseURL = "http://www.example.com"
copyright = ""
defaultContentLanguage = "en"
disqusShortname = ""
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
preserveTaxonomyNames = true
pygmentsCodefences = true
theme = "minimo"
title = "Minimo"
[blackfriday]
hrefTargetBlank = true
[languages.en]
lang = "en"
languageName = "English"
weight = 1
[[menu.main]]
identifier = "repository"
name = "Repo"
url = "https://github.com/MunifTanjim/minimo"
weight = 1
[params.assets]
customcss = ["css/custom.css"]
customjs = ["js/custom.js"]
favicon = "favicon.ico"
gopher = ""
[params.comments]
enable = false
[params.comments.staticman]
apiendpoint = "https://api.staticman.net/v2/entry"
enable = true
maxdepth = 2
[params.comments.staticman.github]
branch = "master"
repository = "minimo"
username = "MunifTanjim"
[params.copyright]
holder = "SkyGIY"
prefix = ""
startyear = "2018"
suffix = ""
[params.info]
description = "Internet of Plants"
title404 = "Nothing's here!"
[params.opengraph.facebook]
admins = []
appid = ""
pageid = ""
[params.opengraph.twitter]
page = ""
[params.seo]
titleseparator = "•"
[params.settings]
accentcolor = "#ffcd00"
archivedateformat = "Jan 02"
dateformat = "2006, Jan 02"
hideentrynavigation = ["page"]
hidemainmenu = false
listdateformat = "2006, Jan 02"
showreadingtime = true
taxonomycloudshuffle = true
[params.sidebar]
enable = true
[params.social]
codepen = ""
email = "lee.saynor@gmail.com"
facebook = ""
github = "leesaynor"
gitlab = ""
google_scholar = ""
instagram = ""
linkedin = ""
telegram = ""
twitter = "skygiy"
[params.widgets]
footer = ["social_menu"]
homepage = ["recent_posts"]
sidebar = ["about", "sidebar_menu", "taxonomy_cloud"]
[permalinks]
page = "/:slug/"
[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
